package com.defiapp.exceptions.customEx;

public enum Exceptions {
    EXCEEDED_LIMIT_PER_USER,
    EXCEEDED_LIMIT_PER_CONTRACT,
    USER_ALREADY_STAKED_AMOUNT,
    USER_HASNT_STAKED_AMOUNT,
    DETERMINED_PERIOD_ISNT_EXPIRED,
    TOKEN_DOESNT_EXIST,
    NOT_STAKED_TOKEN
}
